# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 17:54
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_content_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default=1.0, max_length=5, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoption',
            name='type',
            field=models.IntegerField(choices=[(1, 'Width'), (2, 'Grade')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='option1',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='option2',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Grade'),
        ),
    ]
