# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170719_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=19.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=19.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=19.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=19.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Bundles'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Bundles'),
        ),
    ]
