# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 19:57
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170722_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='square_foot_per_bundle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=5),
        ),
    ]
