# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, default=b'', max_length=300, null=True)),
                ('name', models.CharField(blank=True, default=b'', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default=b'', max_length=32, null=True)),
                ('stacktrace', models.CharField(blank=True, default=b'', max_length=5000, null=True)),
                ('error_type', models.IntegerField(choices=[(1, b'Shipping Weight'), (2, b'Order'), (3, b'Abadon'), (4, b'Shipping Error')], default=1)),
            ],
        ),
    ]
